apiVersion: 1

datasources:
  - name: WAN Influx
    uid: ef5d72wmn4kjkf
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: netmon
    isDefault: true
    jsonData:
      httpMode: POST
